### ISSUE TITLE
Why are vappend / happend so finnicky about matching width/height?

### ISSUE THREAD

**Issue by cwebber** [jeapostrophe/raart#2]
I found that if I used vappend and happend and if the width/height didn't line up (depending on which I used) it complained with 

`; *happend2: Heights must be equal: 1 vs 22`

I figured out that if I used vappend* and happend* they would do the right thing.

The weird thing is that happend and vappaend take `#:halign` and `#:valign` but I can't figure out why they do since they just die if they aren't the same width/height anyway.

**Comment by jeapostrophe** [comment]
`happend` (and `vappend`) should use their `#:valign` (and `#:halign`) arguments to apply `matte` when the heights (and widths) don't match.

`happend*` (and `vappend*`) are just versions of `happend` (and `vappend`) that take a list, rather than many arguments.

**Comment by cwebber** [comment]
Huh, ok!  Maybe i just wasn't supplying #:halign and #:valign when I tested.  Sorry for the false bug, I'm trying to figure out all of this from reading source and examples, so I'm making mistakes :)

**Comment by jeapostrophe** [comment]
It's totally my fault for not writing docs. I really should.

**Comment by cwebber** [comment]
It's cool!  Btw Raart (and Lux generally) are both amazing to use.  I've been working on [a Tetris implementation in Lux](https://octodon.social/@cwebber/100554527454257001) and I almost have a console version working now too using Raart.  It's nice that I can swap in different engines!

**Comment by jeapostrophe** [comment]
Awesome, I'm glad you're liking them!

**Comment by jeapostrophe** [comment]
I pushed some docs.
