### ISSUE TITLE
output different in DrRacket than terminal

### ISSUE THREAD

**Issue by hinkelman** [jeapostrophe/raart#4]
I was playing around with `raart` tonight and I noticed that in DrRacket `(draw-here (text "Hello World!"))` prints as `[0mHello World!`. The same example in the [documentation](https://docs.racket-lang.org/raart/index.html) also shows `[0mHello World!`. However, when I run the same line from the terminal, I get `Hello World!` (as expected).

**Comment by jeapostrophe** [comment]
This is a DrRacket error. It isn't interpreting ANSI color/text style codes.

**Comment by hinkelman** [comment]
Oh, sorry for the misplaced issue. Thanks.
