### ISSUE TITLE
requiring raart tries to open an xorg server because gtk and gui stuff

### ISSUE THREAD

**Issue by cwebber** [jeapostrophe/raart#6]
My friend @brettcs and I have a fun project using raart that we'd love to unleash on the world over telnet.  The problem is that requiring raart does this:

```
Unable to init server: Could not connect: Connection refused
Gtk initialization failed for display ":0"
  context...:
   "/usr/share/racket/pkgs/gui-lib/mred/private/wx/gtk/queue.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   for-loop
   [repeats 1 more time]
   run-module-instance!125
   for-loop
   [repeats 1 more time]
   run-module-instance!125
   do-dynamic-require5
   "/usr/share/racket/pkgs/gui-lib/mred/private/wx/platform.rkt": [running body]
   temp37_0
   for-loop
   run-module-instance!125
   for-loop
   ...
```

Running an xorg process per telnet session seems undesirable for obvious reasons. ;)

It looks like this is because lux-chaos.rkt in raart pulls in the new `kitty.rkt`, which itself imports the GUI library.

**Comment by jeapostrophe** [comment]
I pushed a patch that I think will help

**Comment by cwebber** [comment]
Looks like it fixes it to me!  Thank you so much.
